#!/usr/bin/env sh
/usr/local/bin/xrdb $HOME/.Xresources &
/usr/local/bin/xrdb -merge .Xresources.ocean.dark &
/usr/local/bin/xcompmgr -c &
/usr/local/bin/xrandr --auto &

# Set background using feh
/usr/local/bin/feh --bg-fill  $HOME/Pictures/wallpapers/wallpaper.jpg &

# DWM specific
~/bin/dwm_status_bar.sh &
/usr/local/bin/dwm
